// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF56yfrVkFKoVXkeoPwpmEMs6H_9-cEVg',
    appId: '1:1005011324783:web:031a948fca54912f1ba29a',
    messagingSenderId: '1005011324783',
    projectId: 'npktemperature-b5989',
    authDomain: 'npktemperature-b5989.firebaseapp.com',
    databaseURL: 'https://npktemperature-b5989-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'npktemperature-b5989.firebasestorage.app',
    measurementId: 'G-5NCXV9J47K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmisy-uSPpBpFTzwq_i-Yv9xjj1L9niTI',
    appId: '1:1005011324783:android:6d006847c2d2adea1ba29a',
    messagingSenderId: '1005011324783',
    projectId: 'npktemperature-b5989',
    databaseURL: 'https://npktemperature-b5989-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'npktemperature-b5989.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAahBEQI192wkOX0QZsyIYjftw9nPMYqHY',
    appId: '1:1005011324783:ios:78f7f8b175ebf51f1ba29a',
    messagingSenderId: '1005011324783',
    projectId: 'npktemperature-b5989',
    databaseURL: 'https://npktemperature-b5989-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'npktemperature-b5989.firebasestorage.app',
    iosBundleId: 'com.example.npkTemperature',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAahBEQI192wkOX0QZsyIYjftw9nPMYqHY',
    appId: '1:1005011324783:ios:78f7f8b175ebf51f1ba29a',
    messagingSenderId: '1005011324783',
    projectId: 'npktemperature-b5989',
    databaseURL: 'https://npktemperature-b5989-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'npktemperature-b5989.firebasestorage.app',
    iosBundleId: 'com.example.npkTemperature',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF56yfrVkFKoVXkeoPwpmEMs6H_9-cEVg',
    appId: '1:1005011324783:web:3d481cdf698d1a521ba29a',
    messagingSenderId: '1005011324783',
    projectId: 'npktemperature-b5989',
    authDomain: 'npktemperature-b5989.firebaseapp.com',
    databaseURL: 'https://npktemperature-b5989-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'npktemperature-b5989.firebasestorage.app',
    measurementId: 'G-35RTLF4Y05',
  );
}
